spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/np?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=A1b2c32023!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings for automatic schema creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# impostazione di Jacskon per produrre i json: non mandare i valori nulli
spring.jackson.default-property-inclusion=non_null

